:Author: TONMOYKHANAL
:Email: {AuthorEmail}
:Date: 09/08/2021
:Revision: version#
:License: Public Domain

= Project: The Fire Fighting Robot NAMOR

This code is of a Autonomus Fire Fighting Robot Which uses Three Sensors to check the flame and Get along with it to put it off.
This Project is Submitted to Bangalore University under Registeration Number 18NCS85037

== Step 1: Installation

1. Open this file
2. Edit as you like
3. Release to the World!

== Step 2: Assemble the circuit
Check the Repository for Block Diagram and circuit diagram

== Step 3: Load the code

Upload the code contained in this sketch on to your board

=== Folder structure

....
 sketch123                => Arduino sketch folder
  ├── sketch123.ino       => main Arduino file
  ├── schematics.png      => (optional) an image of the required schematics
  ├── layout.png          => (optional) an image of the layout
  └── ReadMe.adoc         => this file
....

=== License
This project is released under a {License} License.

=== Contributing
To contribute to this project please contact TONMOYKHANAL https://id.arduino.cc/TONMOYKHANAL

=== Components Required
|=== 
| ID | Part name        || Quantity
| 1  |  Flame sensors   || 3
| 2  | AF DC Motors     || 4
| 3  | Arduino UNO      || 1
| 4  | Connecting Wires || 3 set (MM, MF, FM)


=== Help
This document is written in the _AsciiDoc_ format, a markup language to describe documents.
If you need help you can search the http://www.methods.co.nz/asciidoc[AsciiDoc homepage]
or consult the http://powerman.name/doc/asciidoc[AsciiDoc cheatsheet]
